use_frameworks!

platform :ios, '10.0'
source 'https://github.com/RMTelephone/RMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ENABLE_BITCODE'] = 'NO'
#    end
#  end
#end
target 'CltDaLibForOS_Example' do
  pod 'CltDaLibForOS', :path => '../'

  target 'CltDaLibForOS_Tests' do
    inherit! :search_paths

    
  end
end
